"""added timestamp"

Revision ID: 2393818c146a
Revises: e1fee1f1f94b
Create Date: 2019-02-17 03:53:39.193068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2393818c146a'
down_revision = 'e1fee1f1f94b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_artist_timestamp'), 'artist', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_timestamp'), table_name='artist')
    op.drop_column('artist', 'timestamp')
    # ### end Alembic commands ###
