"""word table

Revision ID: 566e145fec8c
Revises: 76686676aafb
Create Date: 2019-02-16 18:47:56.585085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566e145fec8c'
down_revision = '76686676aafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.Column('freq', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_info_word'), 'word_info', ['word'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_info_word'), table_name='word_info')
    op.drop_table('word_info')
    # ### end Alembic commands ###
