"""artist table

Revision ID: 76686676aafb
Revises: 
Create Date: 2019-02-16 18:30:31.086567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76686676aafb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('unique_word_count', sa.Integer(), nullable=True),
    sa.Column('narcissism_rating', sa.DECIMAL(), nullable=True),
    sa.Column('genre', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_genre'), 'artist', ['genre'], unique=False)
    op.create_index(op.f('ix_artist_name'), 'artist', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_name'), table_name='artist')
    op.drop_index(op.f('ix_artist_genre'), table_name='artist')
    op.drop_table('artist')
    # ### end Alembic commands ###
