"""added img_url to artist_info

Revision ID: e1fee1f1f94b
Revises: 566e145fec8c
Create Date: 2019-02-17 03:27:49.165156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fee1f1f94b'
down_revision = '566e145fec8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'img_url')
    # ### end Alembic commands ###
